apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sellerportal-consignment-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/TCGplayer/sellerportal-consignment
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc   # replace with cross-account EKS endpoint
    namespace: sellerportal-consignment

  syncPolicy:
  automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
